name: check_coverage
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check test coverage
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        POORMAN_TOKEN_CODECOV: ${{ secrets.POORMAN_TOKEN_CODECOV }}
      run: sh ci/docker_ci.sh ci/test_coverage.R
